apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jupyterlab
  labels:
    app: jupyterlab
spec:
  selector:
    matchLabels:
      app: jupyterlab
  template:
    metadata:
      labels:
        app: jupyterlab
    spec:
      containers:
      - image: gcr.io/deeplearning-platform-release/base-cpu:m34
        imagePullPolicy: IfNotPresent
        name: jupyterlab
        ports:
        - containerPort: 8080
      serviceAccountName: default