apiVersion: v1
kind: Service
metadata:
  name: jupyterlab-<JUPYTERLAB_ID_SAFE>
  labels:
    app: jupyterlab-<JUPYTERLAB_ID_SAFE>
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: jupyterlab-<JUPYTERLAB_ID_SAFE>