apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: proxy-agent
  labels:
    app: proxy-agent
spec:
  selector:
    matchLabels:
      app: proxy-agent
  template:
    metadata:
      labels:
        app: proxy-agent
    spec:
      containers:
      - image: gcr.io/vkovalevskyi-palyground/agent-gke:m8
        imagePullPolicy: IfNotPresent
        name: proxy-agent
      serviceAccountName: agent-runner